spring:
  datasource:
    url: jdbc:mysql://10.252.252.207:13366/xiongmao_base?characterEncoding=utf8&useSSL=false
    username: xiongmao_base
    password: cEVUtvV6zg,3t*j9hZGf$6=$_RRkeY
  redis:
    database: 40 # Redis数据库索引40
    host: redis-devtest.daqsoft.com # Redis服务器地址
    port: 15818  # Redis服务器连接端口
    password: Redis1231123@#@!!=-23Sdasd1231gjoiuq123#@sda2131-sadas213dsada@#^%&13asdad3412452332