spring:
  datasource:
    url: jdbc:mysql://10.252.252.207:13366/xiongmao_base?characterEncoding=utf8&useSSL=false
    username: xiongmao_base
    password: cEVUtvV6zg,3t*j9hZGf$6=$_RRkeY
  redis:
    database: 7 # Redis数据库索引40
    host: 10.252.252.146 # Redis服务器地址
    port: 10001  # Redis服务器连接端口
    password: nssptestredis