spring:
  datasource:
    url: jdbc:mysql://118.24.34.58:13365/scrs?characterEncoding=utf8&useSSL=false
    username: scrs
    password: D213!@#5423$#1233aGDFREQAS
  redis:
    database: 40 # Redis数据库索引40
    host: redis-devtest.daqsoft.com # Redis服务器地址
    port: 15818  # Redis服务器连接端口
    password: Redis1231123@#@!!=-23Sdasd1231gjoiuq123#@sda2131-sadas213dsada@#^%&13asdad3412452332

mqtt:
  serverURIs: tcp://10.252.249.52:1883
  username: admin
  password: public
  client:
    id: ab123456
  topic: topic_default