spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tb_test?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    database: 40 # Redis数据库索引40
    host: redis-devtest.daqsoft.com # Redis服务器地址
    port: 15818  # Redis服务器连接端口
    password: Redis1231123@#@!!=-23Sdasd1231gjoiuq123#@sda2131-sadas213dsada@#^%&13asdad3412452332